
@base=http://localhost:5000

@user=admin@nxguard.local
@password=admin
@locale=en_US

###
# @name oauth_login
POST {{base}}/nxg/api/oauth/login
Content-Type: application/json

{
  "email": "{{user}}",
  "password": "{{password}}",
  "locale": "{{locale}}"
}

###
# Captura automática dos tokens
@access_token = {{oauth_login.response.body.access_token}}
@refresh_token = {{oauth_login.response.body.refresh_token}}

###
# @name oauth_refresh
GET {{base}}/nxg/api/oauth/token
Content-Type: application/json
Refresh-Token: "{{refresh_token}}"

###
# Captura automática dos tokens
@access_token = {{oauth_refresh.response.body.access_token}}

###
# @name FullIpInfo
# Retrieves comprehensive GeoIP, ASN, and reputation data for a specific IP address.
POST {{base}}/nxg/api/oauth/login
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "email": "admin@nxguard.local",
  "password": "admin",
  "locale": "en_US"
}

