# /etc/sysctl.conf
# vm.max_map_count=262144

services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: unless-stopped
    network_mode: "host"
    #environment:
    #  - REDIS_PASSWORD=supersecreto
    command: [
      "redis-server",
      #  "--requirepass", "supersecreto",
      "--save", "",
      "--appendonly", "no"
    ]
  web:
    image: node:lts
    command: [ "npm", "run", "start" ]
    working_dir: /app
    volumes:
      - ./web:/app
    network_mode: "host"

  api:
    image: liberatti/nxguard:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NXGUARD_ROLE: "main"
      SERVERID: "dev-node"
      PYTHONUNBUFFERED: 1
      REDIS_CACHE_PASS: "admin"
    ports:
      - 5000:5000
      - 80:80
      - 443:443
    init: true
    user: 0
    volumes:
      - ./nxguard:/opt/nxguard/admin
      - ./nxguard/lualib:/opt/nxguard/lualib/share/lua/5.4/nxguard
      - ./nxguard/data:/data
      - /home/liberatti/workspace/.venv/lib/python3.12/site-packages:/opt/nxguard/site-packages
    deploy:
      resources:
        limits:
          memory: 512M
  api_w:
    image: liberatti/nxguard:latest
    environment:
      NXGUARD_ROLE: "worker"
      PYTHONUNBUFFERED: 1
      CLUSTER_ENDPOINT: "http://api/nxg"
    ports:
      - 5010:5000
      - 8010:80
      - 9443:443
    volumes:
      - ./nxguard:/opt/nxguard/admin
      - ./nxguard/lualib:/opt/nxguard/lualib/share/lua/5.4/nxguard
      - /home/liberatti/workspace/.venv/lib/python3.12/site-packages:/opt/nxguard/site-packages
    deploy:
      resources:
        limits:
          memory: 256M

  export:
    image: liberatti/nxguard:export
    build:
      context: .
      dockerfile: Dockerfile
      target: engine
    entrypoint: [ '/bin/bash','-c' ]
    command: [ 'cp /root/rpmbuild/RPMS/*/*.rpm /target' ]
    volumes:
      - ./target:/target

