## IPXA API

###
# @name getIpSet
GET http://localhost:5001/api/feed?type=bypass
Content-Type: application/json

###
# @name ipinfo
POST http://localhost:5001/api/ip/info/1.0.164.165
Content-Type: application/json

response_headers:
```
HTTP/1.1 200 OK
Server: gunicorn
Date: Tue, 28 Jul 2026 16:13:46 GMT
Connection: close
Content-Type: application/json
Content-Length: 419
x-risk-score: 16
x-cache: miss
x-country-code: TH
x-trusted: True
Access-Control-Allow-Origin: *
```

response:
```json
{
  "ip": {
    "address": "1.0.164.165",
    "broadcast": null,
    "network": null,
    "prefix": null,
    "version": null
  },
  "location": {
    "city": "Phuket",
    "continent": "Asia",
    "country": "Thailand",
    "country_code": "TH",
    "latitude": 7.9833,
    "longitude": 98.3662,
    "region": "Phuket"
  },
  "organization": {
    "asn_description": "",
    "asn_name": "",
    "asn_number": ""
  },
  "security": {
    "reasons": [
      "rbl:blocklist_de",
      "rbl:ci_bad_guys",
      "trust:lan_bypass"
    ],
    "risk_score": 16,
    "trusted": true
  }
}
```